<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Portfolio Data Configuration
    |--------------------------------------------------------------------------
    */

    'owner' => [
        'name' => 'Adama Traoré',
        'title' => 'Développeur Full-Stack',
        'status' => 'Full-Stack Dev',
        'email' => 'traoreadama.dev@gmail.com',
        'github' => 'https://github.com/adama-traore-github',
        'linkedin' => 'https://www.linkedin.com/in/adama-traore-dev/',
    ],

    'core_stack' => [
        ['name' => 'Laravel', 'icon' => 'fa-laravel', 'icon_type' => 'brand', 'color' => 'red'],
        ['name' => 'Flutter', 'icon' => 'fa-flutter', 'icon_type' => 'custom', 'color' => 'cyan'],
        ['name' => 'Node.js', 'icon' => 'fa-node-js', 'icon_type' => 'brand', 'color' => 'green'],
        ['name' => 'TailwindCSS', 'icon' => 'fa-css3-alt', 'icon_type' => 'brand', 'color' => 'cyan'],
        ['name' => 'PostgreSQL', 'icon' => 'fa-database', 'icon_type' => 'solid', 'color' => 'emerald'],
        ['name' => 'Docker', 'icon' => 'fa-docker', 'icon_type' => 'brand', 'color' => 'blue'],
    ],

    'skill_categories' => [
        [
            'id' => 'backend',
            'title' => 'Backend & APIs',
            'icon' => 'fa-server',
            'color' => 'green',
            'skills' => [
                ['name' => 'Laravel', 'icon' => 'fa-laravel', 'brand' => true],
                ['name' => 'Node.js / Express', 'icon' => 'fa-node-js', 'brand' => true],
                ['name' => 'PHP 8+', 'icon' => 'fa-php', 'brand' => true],
                ['name' => 'Ruby on Rails', 'icon' => 'fa-gem', 'brand' => false],
                ['name' => 'Python / Django', 'icon' => 'fa-python', 'brand' => true],
                ['name' => 'Java', 'icon' => 'fa-mug-hot', 'brand' => false],
                ['name' => 'API REST & Microservices', 'icon' => 'fa-network-wire', 'brand' => false],
            ]
        ],
        [
            'id' => 'frontend_mobile',
            'title' => 'Frontend & Mobile',
            'icon' => 'fa-mobile-screen',
            'color' => 'cyan',
            'skills' => [
                ['name' => 'Flutter / Dart', 'icon' => 'fa-flutter', 'brand' => false, 'custom' => true],
                ['name' => 'JavaScript (ES6+)', 'icon' => 'fa-js', 'brand' => true],
                ['name' => 'Tailwind CSS', 'icon' => 'fa-css3-alt', 'brand' => true],
                ['name' => 'HTML5 / CSS3', 'icon' => 'fa-html5', 'brand' => true],
                ['name' => 'Bootstrap', 'icon' => 'fa-bootstrap', 'brand' => true],
            ]
        ],
        [
            'id' => 'database_devops',
            'title' => 'Bases de Données & Cloud',
            'icon' => 'fa-database',
            'color' => 'emerald',
            'skills' => [
                ['name' => 'PostgreSQL', 'icon' => 'fa-database', 'brand' => false],
                ['name' => 'MySQL', 'icon' => 'fa-database', 'brand' => false],
                ['name' => 'Supabase', 'icon' => 'fa-bolt', 'brand' => false],
                ['name' => 'Firebase', 'icon' => 'fa-fire', 'brand' => false],
                ['name' => 'Docker', 'icon' => 'fa-docker', 'brand' => true],
                ['name' => 'Git / GitHub', 'icon' => 'fa-git-alt', 'brand' => true],
                ['name' => 'CI / CD Pipelines', 'icon' => 'fa-sliders', 'brand' => false],
            ]
        ],
        [
            'id' => 'web3_emerging',
            'title' => 'Web3 & Innovation',
            'icon' => 'fa-cubes',
            'color' => 'purple',
            'skills' => [
                ['name' => 'Smart Contracts', 'icon' => 'fa-file-contract', 'brand' => false],
                ['name' => 'Intégration Web3', 'icon' => 'fa-cube', 'brand' => false],
                ['name' => 'Token Management', 'icon' => 'fa-coins', 'brand' => false],
                ['name' => 'Méthodes Agiles (Scrum)', 'icon' => 'fa-rotate', 'brand' => false],
                ['name' => 'Assistance IA & Tooling', 'icon' => 'fa-robot', 'brand' => false],
            ]
        ],
    ],

    'knowhows' => [
        ['title' => 'Solutions Web & Mobile', 'desc' => 'Conception globale d’applications web performantes et mobiles multi-plateformes.', 'icon' => 'fa-laptop-code', 'color' => 'cyan'],
        ['title' => 'Architecture API REST & Cloud', 'desc' => 'Développement d’API backend sécurisées, intégrations Stripe et Supabase.', 'icon' => 'fa-network-wire', 'color' => 'green'],
        ['title' => 'Intégration Web3 & Tokenomics', 'desc' => 'Développement de Token Managers et connexion d’applications décentralisées.', 'icon' => 'fa-cubes', 'color' => 'purple'],
        ['title' => 'Bases de Données & DevOps', 'desc' => 'Optimisation PostgreSQL/MySQL, conteneurisation Docker et automatisation Git.', 'icon' => 'fa-database', 'color' => 'emerald'],
    ],

    'projects' => [
        [
            'id' => 'safrimat-immo',
            'title' => 'Safrimat Immo',
            'tech' => 'Flutter / Supabase',
            'color' => 'cyan',
            'category' => 'mobile',
            'category_name' => 'Application Mobile',
            'status_badge' => 'live',
            'status_label' => 'En Production',
            'icon' => 'fa-building-user',
            'desc_key' => 'desc_safrimat_immo',
            'link' => 'https://safrimo.com/',
            'deploy' => 'https://safrimo.com/',
            'mobile_link' => 'https://play.google.com/store/apps/details?id=com.safrimat.safrimat_immo&hl=fr_CH&pli=1',
            'show_github' => false,
            'is_featured' => true,
        ],
        [
            'id' => 'scoops-fab',
            'title' => 'SCOOPS FAB',
            'tech' => 'HTML / CSS / JavaScript',
            'color' => 'emerald',
            'category' => 'web',
            'category_name' => 'Plateforme Web',
            'status_badge' => 'live',
            'status_label' => 'En Production',
            'icon' => 'fa-wheat-awn',
            'desc_key' => 'desc_scoops',
            'link' => '#',
            'deploy' => 'https://scoopsfab.com/',
            'mobile_link' => null,
            'show_github' => false,
            'is_featured' => true,
        ],
        [
            'id' => 'token-manager',
            'title' => 'Token Manager',
            'tech' => 'Blockchain / JS / Web3',
            'color' => 'yellow',
            'category' => 'blockchain',
            'category_name' => 'Web3 & Blockchain',
            'status_badge' => 'live',
            'status_label' => 'Démo En Ligne',
            'icon' => 'fa-cubes',
            'desc_key' => 'desc_token_manager',
            'link' => 'https://github.com/adama-traore-github/Token_Manager_online',
            'deploy' => 'https://web-part-of-the-token-project.vercel.app/',
            'mobile_link' => null,
            'show_github' => true,
            'is_featured' => true,
        ],
        [
            'id' => 'shopeasy',
            'title' => 'ShopEasy',
            'tech' => 'Flutter / Dart',
            'color' => 'indigo',
            'category' => 'mobile',
            'category_name' => 'Application Mobile',
            'status_badge' => 'repo',
            'status_label' => 'Projet Mobile',
            'icon' => 'fa-cart-shopping',
            'desc_key' => 'desc_shopeasy',
            'link' => 'https://github.com/adama-traore-github/shopeasy',
            'deploy' => null,
            'mobile_link' => null,
            'show_github' => true,
            'is_featured' => false,
        ],
        [
            'id' => 'portfolio',
            'title' => 'Portfolio Personnel',
            'tech' => 'Laravel / TailwindCSS',
            'color' => 'red',
            'category' => 'web',
            'category_name' => 'Application Web',
            'status_badge' => 'live',
            'status_label' => 'En Ligne',
            'icon' => 'fa-laptop-code',
            'desc_key' => 'desc_portfolio',
            'link' => 'https://github.com/adama-traore-github/mon_portfolio_avec_laravel',
            'deploy' => 'http://127.0.0.1:8000',
            'mobile_link' => null,
            'show_github' => true,
            'is_featured' => false,
        ],
        [
            'id' => 'immogestion',
            'title' => 'ImmoGestion',
            'tech' => 'Laravel 11 / Breeze',
            'color' => 'purple',
            'category' => 'web',
            'category_name' => 'Plateforme SaaS',
            'status_badge' => 'repo',
            'status_label' => 'Code Source',
            'icon' => 'fa-house-circle-check',
            'desc_key' => 'desc_immo_gestion',
            'link' => 'https://github.com/adama-traore-github/platflorme_gestion_immobiliere',
            'deploy' => null,
            'mobile_link' => null,
            'show_github' => true,
            'is_featured' => false,
        ],
        [
            'id' => 'event-api',
            'title' => 'API Événements & Billetterie',
            'tech' => 'Node.js / Express / Stripe',
            'color' => 'green',
            'category' => 'backend',
            'category_name' => 'API & Microservice',
            'status_badge' => 'repo',
            'status_label' => 'API REST',
            'icon' => 'fa-server',
            'desc_key' => 'desc_event_api',
            'link' => 'https://github.com/adama-traore-github/_site_d_evenement_backend_nodes_js',
            'deploy' => null,
            'mobile_link' => null,
            'show_github' => true,
            'is_featured' => false,
        ],
        [
            'id' => 'event-app',
            'title' => 'App Gestion Événements',
            'tech' => 'Java / Swing',
            'color' => 'orange',
            'category' => 'backend',
            'category_name' => 'Logiciel Java',
            'status_badge' => 'repo',
            'status_label' => 'Projet Java',
            'icon' => 'fa-mug-hot',
            'desc_key' => 'desc_event_app',
            'link' => 'https://github.com/adama-traore-github/EventApp',
            'deploy' => null,
            'mobile_link' => null,
            'show_github' => true,
            'is_featured' => false,
        ],
        [
            'id' => 'task-api',
            'title' => 'API Gestion de Tâches',
            'tech' => 'Node.js / Express / MongoDB',
            'color' => 'green',
            'category' => 'backend',
            'category_name' => 'Backend API',
            'status_badge' => 'repo',
            'status_label' => 'Backend REST',
            'icon' => 'fa-database',
            'desc_key' => 'desc_task_api',
            'link' => 'https://github.com/adama-traore-github/backend_nodes_js_gestion_de_tache',
            'deploy' => null,
            'mobile_link' => null,
            'show_github' => true,
            'is_featured' => false,
        ],
        [
            'id' => 'task-ui',
            'title' => 'Interface Gestion Tâches',
            'tech' => 'HTML / CSS / JS',
            'color' => 'blue',
            'category' => 'web',
            'category_name' => 'Frontend Web',
            'status_badge' => 'repo',
            'status_label' => 'Frontend',
            'icon' => 'fa-list-check',
            'desc_key' => 'desc_task_ui',
            'link' => 'https://github.com/adama-traore-github/frontend_du_projet_gestion_de_tache',
            'deploy' => null,
            'mobile_link' => null,
            'show_github' => true,
            'is_featured' => false,
        ],
        [
            'id' => 'project-planner',
            'title' => 'Project Planner',
            'tech' => 'Django / Python',
            'color' => 'emerald',
            'category' => 'backend',
            'category_name' => 'Application Web & API',
            'status_badge' => 'repo',
            'status_label' => 'Django App',
            'icon' => 'fa-bars-progress',
            'desc_key' => 'desc_project_planner',
            'link' => 'https://github.com/adama-traore-github/application_de_gestion_de_projet',
            'deploy' => null,
            'mobile_link' => null,
            'show_github' => true,
            'is_featured' => false,
        ],
        [
            'id' => 'event-postgres',
            'title' => 'Event Manager Postgres',
            'tech' => 'Ruby on Rails / PostgreSQL',
            'color' => 'red',
            'category' => 'backend',
            'category_name' => 'Backend Rails',
            'status_badge' => 'repo',
            'status_label' => 'Rails & Postgres',
            'icon' => 'fa-gem',
            'desc_key' => 'desc_event_postgres',
            'link' => 'https://github.com/adama-traore-github/event_freka_avec_postgresql',
            'deploy' => null,
            'mobile_link' => null,
            'show_github' => true,
            'is_featured' => false,
        ],
        [
            'id' => 'auction',
            'title' => 'Plateforme Vente aux Enchères',
            'tech' => 'Ruby on Rails',
            'color' => 'red',
            'category' => 'web',
            'category_name' => 'Plateforme Enchères',
            'status_badge' => 'repo',
            'status_label' => 'Code Source',
            'icon' => 'fa-gavel',
            'desc_key' => 'desc_auction',
            'link' => 'https://github.com/adama-traore-github/Biding_war_par_Rahim_et_moi',
            'deploy' => null,
            'mobile_link' => null,
            'show_github' => true,
            'is_featured' => false,
        ],
        [
            'id' => 'task-mobile',
            'title' => 'Task Manager Mobile',
            'tech' => 'Flutter / Dart',
            'color' => 'cyan',
            'category' => 'mobile',
            'category_name' => 'Application Mobile',
            'status_badge' => 'repo',
            'status_label' => 'Mobile App',
            'icon' => 'fa-mobile-screen',
            'desc_key' => 'desc_task_mobile',
            'link' => 'https://github.com/adama-traore-github/apllication_de_gestion_de-tache_avec-fluter',
            'deploy' => null,
            'mobile_link' => null,
            'show_github' => true,
            'is_featured' => false,
        ],
    ],

    'experiences' => [
        [
            'duration' => '7 mois',
            'period' => 'Déc. 2025 – Juil. 2026',
            'company' => 'Safrimat Burkina',
            'role_key' => 'full_stack_dev',
            'type_key' => 'full_time',
            'linkedin' => 'https://www.linkedin.com/company/safrimat-burkina/',
            'desc_key' => 'exp_desc_safrimat',
            'color' => 'emerald',
        ],
        [
            'duration' => '2 ans',
            'period' => '2023 – 2025',
            'company' => 'ETP4A',
            'role_key' => 'full_stack_dev',
            'type_key' => 'part_time',
            'linkedin' => 'https://www.linkedin.com/company/etp4africa/',
            'desc_key' => 'exp_desc_etp4a',
            'color' => 'blue',
        ],
    ],
];
