<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Portfolio Data Configuration
    |--------------------------------------------------------------------------
    */

    'owner' => [
        'name' => 'Adama Traoré',
        'title' => 'Développeur Full-Stack',
        'status' => 'Full-Stack Dev',
        'email' => 'traoreadama.dev@gmail.com',
        'github' => 'https://github.com/adama-traore-github',
        'linkedin' => 'https://www.linkedin.com/in/adama-traore-dev/',
    ],

    'core_stack' => [
        ['name' => 'Laravel', 'level' => 'Expert / Avancé', 'icon' => 'fa-laravel', 'icon_type' => 'brand', 'color' => 'red', 'experience' => '3+ ans'],
        ['name' => 'Flutter', 'level' => 'Maîtrisé', 'icon' => 'fa-flutter', 'icon_type' => 'custom', 'color' => 'cyan', 'experience' => '2+ ans'],
        ['name' => 'Node.js & Express', 'level' => 'Avancé', 'icon' => 'fa-node-js', 'icon_type' => 'brand', 'color' => 'green', 'experience' => '2+ ans'],
        ['name' => 'TailwindCSS', 'level' => 'Expert', 'icon' => 'fa-css3-alt', 'icon_type' => 'brand', 'color' => 'cyan', 'experience' => '3+ ans'],
        ['name' => 'PostgreSQL & MySQL', 'level' => 'Avancé', 'icon' => 'fa-database', 'icon_type' => 'solid', 'color' => 'emerald', 'experience' => '3+ ans'],
        ['name' => 'Docker & DevOps', 'level' => 'Pratique', 'icon' => 'fa-docker', 'icon_type' => 'brand', 'color' => 'blue', 'experience' => '2 ans'],
    ],

    'skill_categories' => [
        [
            'id' => 'languages',
            'title' => 'Langages',
            'icon' => 'fa-code',
            'color' => 'blue',
            'items' => [
                ['name' => 'JavaScript (ES6+)', 'level' => 'Expert', 'icon' => 'fa-js', 'color' => 'yellow'],
                ['name' => 'PHP 8+', 'level' => 'Expert', 'icon' => 'fa-php', 'color' => 'orange'],
                ['name' => 'HTML5 & CSS3', 'level' => 'Expert', 'icon' => 'fa-html5', 'color' => 'orange'],
                ['name' => 'Ruby', 'level' => 'Intermédiaire', 'icon' => 'fa-gem', 'color' => 'red'],
                ['name' => 'Python', 'level' => 'Avancé', 'icon' => 'fa-python', 'color' => 'blue'],
                ['name' => 'Dart', 'level' => 'Avancé', 'icon' => 'fa-code', 'color' => 'cyan'],
                ['name' => 'Java', 'level' => 'Intermédiaire', 'icon' => 'fa-mug-hot', 'color' => 'amber'],
            ]
        ],
        [
            'id' => 'frameworks',
            'title' => 'Frameworks & Libs',
            'icon' => 'fa-cubes',
            'color' => 'green',
            'items' => [
                ['name' => 'Laravel 11/12', 'level' => 'Expert', 'icon' => 'fa-laravel', 'color' => 'red'],
                ['name' => 'Node.js & Express', 'level' => 'Avancé', 'icon' => 'fa-node-js', 'color' => 'green'],
                ['name' => 'Ruby on Rails', 'level' => 'Avancé', 'icon' => 'fa-gem', 'color' => 'red'],
                ['name' => 'Flutter', 'level' => 'Avancé', 'icon' => 'fa-mobile-screen', 'color' => 'cyan'],
                ['name' => 'Bootstrap & Tailwind', 'level' => 'Expert', 'icon' => 'fa-css3-alt', 'color' => 'purple'],
                ['name' => 'Django', 'level' => 'Intermédiaire', 'icon' => 'fa-python', 'color' => 'emerald'],
            ]
        ],
        [
            'id' => 'blockchain',
            'title' => 'Blockchain & Web3',
            'icon' => 'fa-link',
            'color' => 'purple',
            'items' => [
                ['name' => 'Smart Contracts', 'level' => 'Pratique', 'icon' => 'fa-file-contract', 'color' => 'yellow'],
                ['name' => 'Intégration Web3', 'level' => 'Pratique', 'icon' => 'fa-cube', 'color' => 'blue'],
                ['name' => 'Token Management', 'level' => 'Avancé', 'icon' => 'fa-coins', 'color' => 'green'],
            ]
        ],
        [
            'id' => 'databases',
            'title' => 'Bases de données',
            'icon' => 'fa-database',
            'color' => 'emerald',
            'items' => [
                ['name' => 'PostgreSQL', 'level' => 'Avancé', 'icon' => 'fa-database', 'color' => 'blue'],
                ['name' => 'MySQL', 'level' => 'Expert', 'icon' => 'fa-database', 'color' => 'orange'],
                ['name' => 'Supabase', 'level' => 'Avancé', 'icon' => 'fa-bolt', 'color' => 'emerald'],
                ['name' => 'Firebase', 'level' => 'Pratique', 'icon' => 'fa-fire', 'color' => 'amber'],
            ]
        ],
        [
            'id' => 'tools',
            'title' => 'DevOps & Outils',
            'icon' => 'fa-screwdriver-wrench',
            'color' => 'cyan',
            'items' => [
                ['name' => 'Git & GitHub', 'level' => 'Expert', 'icon' => 'fa-git-alt', 'color' => 'orange'],
                ['name' => 'Docker', 'level' => 'Pratique', 'icon' => 'fa-docker', 'color' => 'blue'],
                ['name' => 'CI/CD Pipelines', 'level' => 'Avancé', 'icon' => 'fa-sliders', 'color' => 'indigo'],
                ['name' => 'Trello / Jira', 'level' => 'Avancé', 'icon' => 'fa-trello', 'color' => 'blue'],
            ]
        ],
        [
            'id' => 'process',
            'title' => 'Méthodologies',
            'icon' => 'fa-diagram-project',
            'color' => 'purple',
            'items' => [
                ['name' => 'Méthodologie Agile / Scrum', 'level' => 'Pratique régulière', 'icon' => 'fa-rotate', 'color' => 'purple'],
                ['name' => 'Gestion de Projet', 'level' => 'Pratique', 'icon' => 'fa-tasks', 'color' => 'blue'],
                ['name' => 'Code Reviews & Quality', 'level' => 'Exigeant', 'icon' => 'fa-code-branch', 'color' => 'green'],
                ['name' => 'Assistance IA & Prompting', 'level' => 'Expert', 'icon' => 'fa-robot', 'color' => 'cyan'],
            ]
        ],
    ],

    'knowhows' => [
        ['title' => 'Solutions Web & Mobile Complètes', 'desc' => 'Conception de bout en bout de plateformes web réactives et d’applications mobiles multi-plateformes.', 'icon' => 'fa-laptop-code', 'color' => 'cyan'],
        ['title' => 'Architecture API REST & Microservices', 'desc' => 'Développement d’API backend performantes, sécurisées et intégrées avec Stripe, Supabase et JWT.', 'icon' => 'fa-network-wire', 'color' => 'green'],
        ['title' => 'Méthodologie Agile & Scrum', 'desc' => 'Conduite de projets selon les principes agiles avec itérations rapides et revues de code rigoureuses.', 'icon' => 'fa-sync', 'color' => 'purple'],
        ['title' => 'Intégration Web3 & Smart Contracts', 'desc' => 'Développement de Token Managers et connexion d’applications décentralisées aux protocoles Web3.', 'icon' => 'fa-cubes', 'color' => 'yellow'],
        ['title' => 'Bases de Données & Optimisation', 'desc' => 'Modelisation SQL/NoSQL avancée, gestion d’indexation et d’intégrité des données sous PostgreSQL et MySQL.', 'icon' => 'fa-database', 'color' => 'emerald'],
        ['title' => 'DevOps & Conteneurisation', 'desc' => 'Déploiement et orchestration d’environnements avec Docker, pipelines CI/CD et gestionnaires de version.', 'icon' => 'fa-docker', 'color' => 'blue'],
    ],

    'projects' => [
        [
            'id' => 'safrimat-immo',
            'title' => 'Safrimat Immo',
            'tech' => 'Flutter / Supabase',
            'color' => 'cyan',
            'category' => 'mobile',
            'category_name' => 'Application Mobile',
            'status_badge' => 'live',
            'status_label' => 'En Production',
            'icon' => 'fa-building-user',
            'desc_key' => 'desc_safrimat_immo',
            'link' => 'https://safrimo.com/',
            'deploy' => 'https://safrimo.com/',
            'mobile_link' => 'https://play.google.com/store/apps/details?id=com.safrimat.safrimat_immo&hl=fr_CH&pli=1',
            'show_github' => false,
            'is_featured' => true,
        ],
        [
            'id' => 'scoops-fab',
            'title' => 'SCOOPS FAB',
            'tech' => 'HTML / CSS / JavaScript',
            'color' => 'emerald',
            'category' => 'web',
            'category_name' => 'Plateforme Web',
            'status_badge' => 'live',
            'status_label' => 'En Production',
            'icon' => 'fa-wheat-awn',
            'desc_key' => 'desc_scoops',
            'link' => '#',
            'deploy' => 'https://scoopsfab.com/',
            'mobile_link' => null,
            'show_github' => false,
            'is_featured' => true,
        ],
        [
            'id' => 'token-manager',
            'title' => 'Token Manager',
            'tech' => 'Blockchain / JS / Web3',
            'color' => 'yellow',
            'category' => 'blockchain',
            'category_name' => 'Web3 & Blockchain',
            'status_badge' => 'live',
            'status_label' => 'Démo En Ligne',
            'icon' => 'fa-cubes',
            'desc_key' => 'desc_token_manager',
            'link' => 'https://github.com/adama-traore-github/Token_Manager_online',
            'deploy' => 'https://web-part-of-the-token-project.vercel.app/',
            'mobile_link' => null,
            'show_github' => true,
            'is_featured' => true,
        ],
        [
            'id' => 'shopeasy',
            'title' => 'ShopEasy',
            'tech' => 'Flutter / Dart',
            'color' => 'indigo',
            'category' => 'mobile',
            'category_name' => 'Application Mobile',
            'status_badge' => 'repo',
            'status_label' => 'Projet Mobile',
            'icon' => 'fa-cart-shopping',
            'desc_key' => 'desc_shopeasy',
            'link' => 'https://github.com/adama-traore-github/shopeasy',
            'deploy' => null,
            'mobile_link' => null,
            'show_github' => true,
            'is_featured' => false,
        ],
        [
            'id' => 'portfolio',
            'title' => 'Portfolio Personnel',
            'tech' => 'Laravel / TailwindCSS',
            'color' => 'red',
            'category' => 'web',
            'category_name' => 'Application Web',
            'status_badge' => 'live',
            'status_label' => 'En Ligne',
            'icon' => 'fa-laptop-code',
            'desc_key' => 'desc_portfolio',
            'link' => 'https://github.com/adama-traore-github/mon_portfolio_avec_laravel',
            'deploy' => 'http://127.0.0.1:8000',
            'mobile_link' => null,
            'show_github' => true,
            'is_featured' => false,
        ],
        [
            'id' => 'immogestion',
            'title' => 'ImmoGestion',
            'tech' => 'Laravel 11 / Breeze',
            'color' => 'purple',
            'category' => 'web',
            'category_name' => 'Plateforme SaaS',
            'status_badge' => 'repo',
            'status_label' => 'Code Source',
            'icon' => 'fa-house-circle-check',
            'desc_key' => 'desc_immo_gestion',
            'link' => 'https://github.com/adama-traore-github/platflorme_gestion_immobiliere',
            'deploy' => null,
            'mobile_link' => null,
            'show_github' => true,
            'is_featured' => false,
        ],
        [
            'id' => 'event-api',
            'title' => 'API Événements & Billetterie',
            'tech' => 'Node.js / Express / Stripe',
            'color' => 'green',
            'category' => 'backend',
            'category_name' => 'API & Microservice',
            'status_badge' => 'repo',
            'status_label' => 'API REST',
            'icon' => 'fa-server',
            'desc_key' => 'desc_event_api',
            'link' => 'https://github.com/adama-traore-github/_site_d_evenement_backend_nodes_js',
            'deploy' => null,
            'mobile_link' => null,
            'show_github' => true,
            'is_featured' => false,
        ],
        [
            'id' => 'event-app',
            'title' => 'App Gestion Événements',
            'tech' => 'Java / Swing',
            'color' => 'orange',
            'category' => 'backend',
            'category_name' => 'Logiciel Java',
            'status_badge' => 'repo',
            'status_label' => 'Projet Java',
            'icon' => 'fa-mug-hot',
            'desc_key' => 'desc_event_app',
            'link' => 'https://github.com/adama-traore-github/EventApp',
            'deploy' => null,
            'mobile_link' => null,
            'show_github' => true,
            'is_featured' => false,
        ],
        [
            'id' => 'task-api',
            'title' => 'API Gestion de Tâches',
            'tech' => 'Node.js / Express / MongoDB',
            'color' => 'green',
            'category' => 'backend',
            'category_name' => 'Backend API',
            'status_badge' => 'repo',
            'status_label' => 'Backend REST',
            'icon' => 'fa-database',
            'desc_key' => 'desc_task_api',
            'link' => 'https://github.com/adama-traore-github/backend_nodes_js_gestion_de_tache',
            'deploy' => null,
            'mobile_link' => null,
            'show_github' => true,
            'is_featured' => false,
        ],
        [
            'id' => 'task-ui',
            'title' => 'Interface Gestion Tâches',
            'tech' => 'HTML / CSS / JS',
            'color' => 'blue',
            'category' => 'web',
            'category_name' => 'Frontend Web',
            'status_badge' => 'repo',
            'status_label' => 'Frontend',
            'icon' => 'fa-list-check',
            'desc_key' => 'desc_task_ui',
            'link' => 'https://github.com/adama-traore-github/frontend_du_projet_gestion_de_tache',
            'deploy' => null,
            'mobile_link' => null,
            'show_github' => true,
            'is_featured' => false,
        ],
        [
            'id' => 'project-planner',
            'title' => 'Project Planner',
            'tech' => 'Django / Python',
            'color' => 'emerald',
            'category' => 'backend',
            'category_name' => 'Application Web & API',
            'status_badge' => 'repo',
            'status_label' => 'Django App',
            'icon' => 'fa-bars-progress',
            'desc_key' => 'desc_project_planner',
            'link' => 'https://github.com/adama-traore-github/application_de_gestion_de_projet',
            'deploy' => null,
            'mobile_link' => null,
            'show_github' => true,
            'is_featured' => false,
        ],
        [
            'id' => 'event-postgres',
            'title' => 'Event Manager Postgres',
            'tech' => 'Ruby on Rails / PostgreSQL',
            'color' => 'red',
            'category' => 'backend',
            'category_name' => 'Backend Rails',
            'status_badge' => 'repo',
            'status_label' => 'Rails & Postgres',
            'icon' => 'fa-gem',
            'desc_key' => 'desc_event_postgres',
            'link' => 'https://github.com/adama-traore-github/event_freka_avec_postgresql',
            'deploy' => null,
            'mobile_link' => null,
            'show_github' => true,
            'is_featured' => false,
        ],
        [
            'id' => 'auction',
            'title' => 'Plateforme Vente aux Enchères',
            'tech' => 'Ruby on Rails',
            'color' => 'red',
            'category' => 'web',
            'category_name' => 'Plateforme Enchères',
            'status_badge' => 'repo',
            'status_label' => 'Code Source',
            'icon' => 'fa-gavel',
            'desc_key' => 'desc_auction',
            'link' => 'https://github.com/adama-traore-github/Biding_war_par_Rahim_et_moi',
            'deploy' => null,
            'mobile_link' => null,
            'show_github' => true,
            'is_featured' => false,
        ],
        [
            'id' => 'task-mobile',
            'title' => 'Task Manager Mobile',
            'tech' => 'Flutter / Dart',
            'color' => 'cyan',
            'category' => 'mobile',
            'category_name' => 'Application Mobile',
            'status_badge' => 'repo',
            'status_label' => 'Mobile App',
            'icon' => 'fa-mobile-screen',
            'desc_key' => 'desc_task_mobile',
            'link' => 'https://github.com/adama-traore-github/apllication_de_gestion_de-tache_avec-fluter',
            'deploy' => null,
            'mobile_link' => null,
            'show_github' => true,
            'is_featured' => false,
        ],
    ],

    'experiences' => [
        [
            'duration' => '1 an',
            'company' => 'Safrimat Burkina',
            'role_key' => 'full_stack_dev',
            'type_key' => 'full_time',
            'linkedin' => 'https://www.linkedin.com/company/safrimat-burkina/',
            'desc_key' => 'exp_desc_safrimat',
            'color' => 'emerald',
        ],
        [
            'duration' => '2 ans',
            'company' => 'ETP4A',
            'role_key' => 'full_stack_dev',
            'type_key' => 'part_time',
            'linkedin' => 'https://www.linkedin.com/company/etp4africa/',
            'desc_key' => 'exp_desc_etp4a',
            'color' => 'blue',
        ],
    ],
];
