<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Portfolio Data Configuration
    |--------------------------------------------------------------------------
    */

    'owner' => [
        'name' => 'Adama Traoré',
        'title' => 'Ingénieur Logiciel Full-Stack | Laravel · Flutter · Node.js',
        'status' => 'Ouvert aux opportunités | Full-Stack Web & Mobile',
        'email' => 'traoreadama.dev@gmail.com',
        'github' => 'https://github.com/adama-traore-github',
        'linkedin' => 'https://www.linkedin.com/in/adama-traore-dev/',
        'cv_link' => '/cv/CV_Adama_Traore.pdf',
        'show_cv' => false,
    ],

    'core_stack' => [
        ['name' => 'Laravel', 'icon' => 'fa-laravel', 'icon_type' => 'brand', 'color' => 'red'],
        ['name' => 'Flutter', 'icon' => 'fa-flutter', 'icon_type' => 'custom', 'color' => 'cyan'],
        ['name' => 'Node.js', 'icon' => 'fa-node-js', 'icon_type' => 'brand', 'color' => 'green'],
        ['name' => 'PostgreSQL', 'icon' => 'fa-database', 'icon_type' => 'solid', 'color' => 'emerald'],
        ['name' => 'TailwindCSS', 'icon' => 'fa-css3-alt', 'icon_type' => 'brand', 'color' => 'cyan'],
        ['name' => 'Docker', 'icon' => 'fa-docker', 'icon_type' => 'brand', 'color' => 'blue'],
    ],

    'skill_categories' => [
        [
            'id' => 'backend',
            'title' => 'Architecture Backend & APIs',
            'icon' => 'fa-server',
            'color' => 'green',
            'skills' => [
                ['name' => 'Laravel 11 / PHP 8+', 'icon' => 'fa-laravel', 'brand' => true],
                ['name' => 'Node.js / Express', 'icon' => 'fa-node-js', 'brand' => true],
                ['name' => 'Conception d\'APIs RESTful', 'icon' => 'fa-network-wire', 'brand' => false],
                ['name' => 'Sécurité Applicative & OWASP', 'icon' => 'fa-shield-halved', 'brand' => false],
            ]
        ],
        [
            'id' => 'frontend_mobile',
            'title' => 'Développement Mobile & Frontend',
            'icon' => 'fa-mobile-screen',
            'color' => 'cyan',
            'skills' => [
                ['name' => 'Flutter / Dart (iOS & Android)', 'icon' => 'fa-flutter', 'brand' => false, 'custom' => true],
                ['name' => 'Tailwind CSS & JS (ES6+)', 'icon' => 'fa-css3-alt', 'brand' => true],
                ['name' => 'Interfaces Web Responsive', 'icon' => 'fa-display', 'brand' => false],
                ['name' => 'Gestion d\'État Mobile', 'icon' => 'fa-diagram-project', 'brand' => false],
            ]
        ],
        [
            'id' => 'databases_cloud',
            'title' => 'Bases de Données & Services Cloud',
            'icon' => 'fa-database',
            'color' => 'purple',
            'skills' => [
                ['name' => 'BDD Relationnelles (PostgreSQL, MySQL)', 'icon' => 'fa-database', 'brand' => false],
                ['name' => 'BDD NoSQL & BaaS (Supabase, Firebase)', 'icon' => 'fa-bolt', 'brand' => false],
                ['name' => 'Modélisation & Optimisation SQL', 'icon' => 'fa-table-cells', 'brand' => false],
                ['name' => 'Intégration de Paiement (Stripe)', 'icon' => 'fa-credit-card', 'brand' => false],
            ]
        ],
        [
            'id' => 'devops_tools',
            'title' => 'DevOps & Intégration Continue',
            'icon' => 'fa-screwdriver-wrench',
            'color' => 'emerald',
            'skills' => [
                ['name' => 'Conteneurisation Docker', 'icon' => 'fa-docker', 'brand' => true],
                ['name' => 'Git / GitHub Actions (CI/CD)', 'icon' => 'fa-git-alt', 'brand' => true],
                ['name' => 'Environnement Linux / Bash', 'icon' => 'fa-terminal', 'brand' => false],
                ['name' => 'Gestion de projet Agile (Scrum)', 'icon' => 'fa-rotate', 'brand' => false],
            ]
        ],
    ],

    'knowhows' => [
        ['title' => 'Conception Web & Mobile', 'desc' => 'Développement d’applications web réactives et mobiles multi-plateformes performantes avec Laravel et Flutter.', 'icon' => 'fa-laptop-code', 'color' => 'cyan'],
        ['title' => 'Conception d\'APIs REST & Microservices', 'desc' => 'Conception d\'APIs sécurisées, modulaires et documentées avec authentification JWT/Sanctum et paiements tiers.', 'icon' => 'fa-network-wire', 'color' => 'green'],
        ['title' => 'Bases de Données & Modélisation', 'desc' => 'Modélisation relationnelle avancée (PostgreSQL, MySQL) et intégrations temps réel Supabase.', 'icon' => 'fa-database', 'color' => 'emerald'],
        ['title' => 'DevOps & Intégration Continue', 'desc' => 'Conteneurisation avec Docker, automatisation des tests et pipelines CI/CD sur GitHub Actions.', 'icon' => 'fa-docker', 'color' => 'blue'],
    ],

    'projects' => [
        [
            'id' => 'safrimat-immo-mobile',
            'title' => 'Safrimat Immo (Mobile)',
            'tech' => 'Flutter / Supabase',
            'color' => 'purple',
            'category' => 'mobile',
            'category_name' => 'Application Mobile',
            'status_badge' => 'live',
            'status_label' => 'Google Play',
            'icon' => 'fa-mobile-screen-button',
            'desc_key' => 'desc_safrimat_immo_mobile',
            'link' => '#',
            'deploy' => null,
            'mobile_link' => 'https://play.google.com/store/apps/details?id=com.safrimat.safrimat_immo&hl=fr_CH&pli=1',
            'show_github' => false,
            'is_featured' => true,
        ],
        [
            'id' => 'fruit-legumes-nutrition',
            'title' => 'Fruits & Légumes (Coach IA)',
            'tech' => 'Flutter / Firebase / IA',
            'color' => 'emerald',
            'category' => 'mobile',
            'category_name' => 'Application Mobile',
            'status_badge' => 'mobile',
            'status_label' => 'Google Play',
            'icon' => 'fa-carrot',
            'desc_key' => 'desc_fruit_legumes',
            'link' => '#',
            'deploy' => null,
            'mobile_link' => 'https://play.google.com/store/apps/details?id=com.safrimat.fruits_legumes_app&hl=fr',
            'show_github' => false,
            'is_featured' => true,
        ],
        [
            'id' => 'secure-protocol',
            'title' => 'SecureProtocol',
            'tech' => 'Node.js / Web Crypto API',
            'color' => 'purple',
            'category' => 'backend',
            'category_name' => 'Sécurité & Cryptographie',
            'status_badge' => 'private',
            'status_label' => 'Repo Privé',
            'icon' => 'fa-shield-halved',
            'desc_key' => 'desc_secure_protocol',
            'link' => '#',
            'deploy' => 'https://www.npmjs.com/package/secure-protocol',
            'mobile_link' => null,
            'show_github' => false,
            'is_featured' => true,
        ],
        [
            'id' => 'gestion-locative',
            'title' => 'Gestion Locative',
            'tech' => 'Node.js / React / Prisma',
            'color' => 'blue',
            'category' => 'web backend',
            'category_name' => 'Plateforme SaaS & API',
            'status_badge' => 'private',
            'status_label' => 'Repo Privé',
            'icon' => 'fa-building-user',
            'desc_key' => 'desc_gestion_locative',
            'link' => '#',
            'deploy' => 'soon',
            'mobile_link' => null,
            'show_github' => false,
            'is_featured' => true,
        ],
        [
            'id' => 'i-love-sticker',
            'title' => 'I Love Sticker',
            'tech' => 'Node.js / Express / APIs',
            'color' => 'orange',
            'category' => 'web backend',
            'category_name' => 'Plateforme Web & API',
            'status_badge' => 'live',
            'status_label' => 'En Production',
            'icon' => 'fa-globe',
            'desc_key' => 'desc_i_love_sticker',
            'link' => '#',
            'deploy' => 'https://ilovestickers.app/',
            'mobile_link' => null,
            'show_github' => false,
            'is_featured' => true,
        ],
        [
            'id' => 'mon-portfolio',
            'title' => 'Mon Portfolio',
            'tech' => 'Laravel 11 / Tailwind / Blade',
            'color' => 'cyan',
            'category' => 'web',
            'category_name' => 'Plateforme Web',
            'status_badge' => 'live',
            'status_label' => 'En Production',
            'icon' => 'fa-laptop-code',
            'desc_key' => 'desc_mon_portfolio',
            'link' => 'https://github.com/adama-traore-github/mon_portfolio_avec_laravel',
            'deploy' => 'https://adama-traore.me/',
            'mobile_link' => null,
            'show_github' => true,
            'is_featured' => true,
        ],
        [
            'id' => 'scoops-fab',
            'title' => 'SCOOPS FAB',
            'tech' => 'HTML5 / CSS3 / JavaScript',
            'color' => 'emerald',
            'category' => 'web',
            'category_name' => 'Plateforme Web',
            'status_badge' => 'live',
            'status_label' => 'En Production',
            'icon' => 'fa-wheat-awn',
            'desc_key' => 'desc_scoops',
            'link' => 'https://scoopsfab.com/',
            'deploy' => 'https://scoopsfab.com/',
            'mobile_link' => null,
            'show_github' => false,
            'is_featured' => true,
        ],
        [
            'id' => 'safrimat-immo-web',
            'title' => 'Safrimat Immo (Web)',
            'tech' => 'Flutter Web / Supabase',
            'color' => 'cyan',
            'category' => 'web',
            'category_name' => 'Plateforme Web',
            'status_badge' => 'live',
            'status_label' => 'En Production',
            'icon' => 'fa-globe',
            'desc_key' => 'desc_safrimat_immo_web',
            'link' => '#',
            'deploy' => 'https://safrimo.com/',
            'mobile_link' => null,
            'show_github' => false,
            'is_featured' => true,
        ],
        [
            'id' => 'event-api',
            'title' => 'API Événements & Billetterie',
            'tech' => 'Node.js / Express / Stripe',
            'color' => 'green',
            'category' => 'backend',
            'category_name' => 'API REST & Service',
            'status_badge' => 'repo',
            'status_label' => 'API REST',
            'icon' => 'fa-server',
            'desc_key' => 'desc_event_api',
            'link' => 'https://github.com/adama-traore-github/_site_d_evenement_backend_nodes_js',
            'deploy' => null,
            'mobile_link' => null,
            'show_github' => true,
            'is_featured' => true,
        ],
        [
            'id' => 'shopeasy',
            'title' => 'ShopEasy',
            'tech' => 'Flutter / Dart / REST API',
            'color' => 'indigo',
            'category' => 'mobile',
            'category_name' => 'Application Mobile',
            'status_badge' => 'repo',
            'status_label' => 'Projet Mobile',
            'icon' => 'fa-cart-shopping',
            'desc_key' => 'desc_shopeasy',
            'link' => 'https://github.com/adama-traore-github/shopeasy',
            'deploy' => null,
            'mobile_link' => null,
            'show_github' => true,
            'is_featured' => true,
        ],
        [
            'id' => 'immogestion',
            'title' => 'ImmoGestion',
            'tech' => 'Laravel 11 / Breeze',
            'color' => 'purple',
            'category' => 'web',
            'category_name' => 'Plateforme SaaS',
            'status_badge' => 'repo',
            'status_label' => 'Code Source',
            'icon' => 'fa-house-circle-check',
            'desc_key' => 'desc_immo_gestion',
            'link' => 'https://github.com/adama-traore-github/platflorme_gestion_immobiliere',
            'deploy' => null,
            'mobile_link' => null,
            'show_github' => true,
            'is_featured' => true,
        ],
    ],

    'experiences' => [
        [
            'duration' => '1 an 8 mois',
            'period' => 'Déc. 2024 – Juil. 2026',
            'company' => 'Safrimat Burkina',
            'role_key' => 'full_stack_dev_cdd',
            'type_key' => 'full_time',
            'linkedin' => 'https://www.linkedin.com/company/safrimat-burkina/',
            'desc_key' => 'exp_desc_safrimat',
            'color' => 'emerald',
        ],
        [
            'duration' => '2 ans',
            'period' => 'Oct. 2024 – Présent',
            'company' => 'ETP4A',
            'location_type' => 'Remote',
            'role_key' => 'tech_mentor_trainer',
            'type_key' => 'part_time',
            'linkedin' => 'https://www.linkedin.com/company/etp4africa/',
            'desc_key' => 'exp_desc_etp4a',
            'color' => 'blue',
        ],
    ],
];

